name: fluttertest
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  video_player: ^2.9.2
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  firebase_storage: ^12.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17  # Giữ phiên bản này, không cần dòng flutter_svg khác
  carousel_slider: ^5.0.0
  firebase_core: ^3.11.0  # Phiên bản mới nhất hiện tại
  firebase_auth: ^5.4.2
  firebase_database: ^11.3.2  # Nếu bạn dùng Firebase Realtime Database
  cloud_firestore: ^5.6.3
  curved_navigation_bar: ^1.0.3

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


